# Generated by Django 3.1.5 on 2021-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('leader', models.CharField(max_length=40)),
                ('harvesting_type', models.IntegerField()),
                ('location', models.CharField(max_length=45)),
                ('farmers', models.CharField(max_length=45)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=255)),
                ('idnumber', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('harvesting', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cooperative', models.CharField(max_length=90)),
                ('farmer', models.CharField(max_length=40)),
                ('Quantity', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=45)),
            ],
        ),
    ]
