# Generated by Django 3.1.5 on 2021-01-17 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmers',
            name='harvesting',
        ),
        migrations.AlterField(
            model_name='cooperatives',
            name='harvesting_type',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='record',
            name='cooperative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cooperatives'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
