# Generated by Django 3.1.5 on 2021-01-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210117_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='farmers',
            name='Site',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('farmers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.farmers')),
            ],
        ),
        migrations.AddField(
            model_name='cooperatives',
            name='Site',
            field=models.OneToOneField(default='Site', on_delete=django.db.models.deletion.CASCADE, to='home.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.site'),
            preserve_default=False,
        ),
    ]
