# Generated by Django 3.1.5 on 2021-01-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210125_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperatives',
            name='Site',
        ),
        migrations.RemoveField(
            model_name='record',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='record',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='record',
            name='site',
        ),
        migrations.DeleteModel(
            name='Recorder',
        ),
        migrations.RemoveField(
            model_name='site',
            name='farmers',
        ),
        migrations.DeleteModel(
            name='Cooperatives',
        ),
        migrations.DeleteModel(
            name='Farmers',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
